<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- This sets defaults, needed for tooling (e.g. Intellisense) to understand what to build -->
    <Platforms>x64</Platforms>
    <Configurations>Debug;Release;Run</Configurations>

    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    
    <PackageId>Gossamer</PackageId>
    <Version>0.0.1</Version>

    <!-- Get rid of the "netX.X" in the output path -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <!-- In Run configuration, define the RUN constant and set the output type to Exe -->
  <PropertyGroup Condition="'$(Configuration)' == 'Run'">
    <DefineConstants>RUN</DefineConstants>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <!-- References -->
  <ItemGroup>
    <Using Include="System.Numerics" />
  </ItemGroup>

  <!-- Embedded -->
  <ItemGroup>
    <EmbeddedResource Include="Gfx/Text/ProggyClean.ttf" />
    <EmbeddedResource Include="Gfx/Shaders/built-in.shaders" />
  </ItemGroup>

  <!-- Dependency binaries for Windows -->
  <ItemGroup Condition=" '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' ">
    <!-- GLFW -->
    <None Update="External/libgossamer-glfw.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- FreeType -->
    <None Update="External/libgossamer-freetype.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- HarfBuzz -->
    <None Update="External/libgossamer-harfbuzz.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- Vulkan Memory Allocator -->
    <None Update="External/Gossamer.Vma.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- WebP -->
    <None Update="External/Gossamer.WebP.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Dependency binaries for Linux -->
  <ItemGroup Condition=" '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' ">
    <!-- GLFW -->
    <None Update="External/libgossamer-glfw.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- FreeType -->
    <None Update="External/libgossamer-freetype.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- HarfBuzz -->
    <None Update="External/libgossamer-harfbuzz.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- Vulkan Memory Allocator -->
    <None Update="External/Gossamer.Vma.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <!-- WebP -->
    <None Update="External/Gossamer.WebP.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
