<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Platforms>x64</Platforms>
    <Configurations>Debug;Release</Configurations>
    <OutputType>Exe</OutputType>
    
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>

    <PackageId>Gossamer.Benchmark</PackageId>
    <Version>0.0.1</Version>

  <!-- Get rid of the "netX.X" in the output path -->
  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Gossamer/Gossamer.csproj" />
  </ItemGroup>

</Project>
